import json
import re

from app.core.exceptions import (
    LLMException
)


def parse_llm_json(content: str):

    try:

        cleaned = re.sub(
            r"```json|```",
            "",
            content
        ).strip()

        return json.loads(cleaned)

    except Exception:

        raise LLMException(
            detail="Invalid JSON generated by Gemini"
        )